export const STARTERS: Record<'easy' | 'hard', Record<number, string[]>> = {
  easy: {
    3: ["ARE", "ATE", "EAR", "ONE", "ORE", "USE", "EAT", "TEA", "TAR", "RAT"],
    4: ["TALE", "LEST", "SALT", "LAST", "LENT", "TERN", "PELT", "LATE", "RANT", "RALE", "LARD", "MELT", "SLAT", "TOLE", "TARN", "LEPT", "RENT", "TELS", "TARE", "DELT"],
    5: ["SALET", "REAST", "CRATE", "TRACE", "SLATE", "TRINE", "CRANE", "SLANT", "CARLE", "SLANE", "STALE", "CARTE", "RANCE", "TORSE", "TRADE", "CARSE", "TRAPE", "LEANT", "SNARE", "REACT"],
    6: ["SALTER", "DARTLE", "LASTER", "SLATER", "SALTED", "RANTED", "DARNEL", "TAILER", "MATIER", "STALER", "SAILER", "AIRTED", "TAILED", "RAILED", "ANTLER", "NAILER", "LOANER"],
    7: ["SALTIRE", "SALTIER", "REALIST", "SLATIER", "SORTIED", "PASTIER", "NASTIER", "MALTIER", "COALIER", "PLATIER", "SAUNTER", "SCALIER", "CLARIES", "ANTSIER", "TARDIES"],
    8: ["CERATINS", "SENORITA", "CALORIES", "NOTARIES", "DETRAINS", "COSTLIER", "SODALITE", "CANISTER", "AUNTLIER", "SCANTIER"],
  },
  hard: {
    3: ["ARE", "ATE", "EAR", "ONE", "ORE", "USE", "EAT", "TEA", "TAR", "RAT"],
    4: ["DALS", "CELT", "REST", "RENT", "TARN", "TRES", "RANT", "LAST", "LARS", "LATS", "MELT", "SALT", "ROTL", "TOLE", "MELS", "RETS", "MALE", "LEAR", "LEST", "TELS"],
    5: ["TRACE", "SALET", "SLATE", "LEANT", "REAST", "CRATE", "LEAST", "SLANE", "CARLE", "CRANE", "PRATE", "SLANT", "CARTE", "CARET", "CLAST", "TRINE", "REACT", "TEALS", "TORSE", "TRAIL"],
    6: ["SALTIE", "CASTLE", "SATIRE", "SANTIR", "CANTLE", "CARTES", "SAMLET", "LISTEN", "CARNET", "CARTEL", "SORTIE", "SALTER", "LANCET", "TINSEL", "MANTEL", "SALTED", "SALINE", "RELIST", "MANTES", "SANTOL"],
    7: ["SALTIRE", "SALTIER", "CANTLES", "SLATIER", "SCARLET", "TRANCES", "SCANTER", "DARTLES", "HARSLET", "PLASTER", "PSALTER", "PLANTER", "STAPLER", "WRASTLE", "BORSCHT", "LAMSTER", "RATLINS", "SLATHER", "SMARTEN", "SNORTED"],
    8: ["CERATINS", "CENTRALS", "SENORITA", "CALORIES", "SODALITE", "COSTLIER", "NOTARIES", "DETRAINS", "AUNTLIER", "CALDRONS", "SCANTIER", "TENDRILS"],
  }
};
